INSERT OR IGNORE INTO categories (slug, label, group_name, sort_order) VALUES
  ('gmail', 'Gmail', 'email', 1),
  ('hotmail', 'HotMail', 'email', 2),
  ('outlookmail', 'OutlookMail', 'email', 3),
  ('rumail', 'RuMail', 'email', 4),
  ('email-domain', 'Email tên miền', 'email', 5),
  ('yahoo', 'YahooMail', 'email', 6),
  ('protonmail', 'ProtonMail', 'email', 7),
  ('other-email', 'Các loại Email khác', 'email', 8),
  ('windows', 'Windows', 'software', 1),
  ('office', 'Office', 'software', 2),
  ('adobe', 'Adobe', 'software', 3),
  ('tools', 'Tools', 'software', 4),
  ('game', 'Game', 'accounts', 1),
  ('social', 'Mạng xã hội', 'accounts', 2),
  ('cloud', 'Cloud', 'accounts', 3),
  ('other', 'Khác', 'other', 1);
